# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NowPlayingList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Then'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  # Pods for NowPlayingList

  target 'NowPlayingListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
